# Generated by Django 6.0.2 on 2026-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='created_at',
            new_name='setup_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools')], default='frontend', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='fjjncfjn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='shree.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
