# Generated by Django 6.0.2 on 2026-03-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_rename_created_at_skill_setup_date_remove_skill_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('setup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='frontend', max_length=20),
        ),
    ]
