# Generated by Django 6.0.2 on 2026-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_resume_title_resume_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='skills/'),
        ),
    ]
