# Generated by Django 6.0.2 on 2026-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_name', models.CharField(max_length=255)),
                ('Certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('Certificate_description', models.TextField(max_length=40)),
                ('Certificate_link', models.URLField()),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
