# Generated by Django 6.0.2 on 2026-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Badge_name', models.CharField(max_length=255)),
                ('Badge_image', models.ImageField(upload_to='badges/')),
                ('Badge_link', models.URLField()),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Certificate_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Certificate_image',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
