# Generated by Django 6.0.2 on 2026-03-01 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
